#下面这些内容是为了让MyBatis映射
mybatis:
  mapper-locations: classpath*:mapper/*.xml #指定Mybatis的Mapper文件
  type-aliases-package: com.owen.entity #指定Mybatis的实体目录
shiro:
  loginUrl: /login.html
spring:
  application:
    name: Shiro-Springboot
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro-web?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&userSSL=false&tinyIntlisBit=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
#    password: Owen@2022
